language: java
jdk:
  - openjdk21

install:
  - mvn install -DskipTests


script:
  - mvn exec:java@serveur &
  - echo "le premier build n'est pas passé car le serveur n'avait pas eu le temps de se lancer..., attente de quelques secondes pour laisser le temps de démarrer"
  - sleep 5
  - mvn exec:java@client -Dexec.cleanupDaemonThreads=false