language: java
jdk:
  - openjdk17

install:
  - mvn install -DskipTests


script:
  - mvn exec:java@serveur &
  - mvn exec:java@client -Dexec.cleanupDaemonThreads=false
  - echo "fin violente"
  - kill -9 -1